export const DAILY_PROMPTS = [
  "What's something unspoken you've been carrying?",
  "Describe a moment you wish you could relive.",
  "If you could say anything without consequence, what would it be?",
  "What dream keeps visiting your thoughts lately?",
  "Write about a hope you rarely voice aloud.",
  "Recall a lesson learned the hard way.",
  "What small act of kindness stayed with you?",
  "Name a fear you'd like to release.",
  "Describe a place that makes you feel safe.",
  "What do you long to forgive yourself for?",
  "Share a memory that still makes you smile.",
  "Write about a secret wish you hold.",
  "How have you changed in the last year?",
  "What makes your heart feel heavy today?",
  "Describe a time you felt truly seen.",
  "What would you do if you knew you couldn't fail?",
  "Recall a conversation you wish went differently.",
  "What does healing look like for you?",
  "Write the words you most needed to hear as a child.",
  "What breaks your heart about the world?",
  "Describe a simple joy you often overlook.",
  "When do you feel most like yourself?",
  "What does your perfect day include?",
  "Write about a bridge you want to rebuild.",
  "What hope keeps you moving forward?",
  "How do you show love to others?",
  "What part of yourself needs more compassion?",
  "Describe a moment that changed your perspective.",
  "What do you want to celebrate about yourself?",
  "Name something you've outgrown.",
  "Where do you feel a sense of belonging?",
  "What are you ready to let go of?",
  "Write about a risk worth taking.",
  "How do you recharge your spirit?",
  "What relationship needs more attention?",
  "Describe a promise you want to keep to yourself.",
  "When did you last feel hopeful?",
  "What personal boundary do you need to strengthen?",
  "Write about a time you surprised yourself.",
  "How do you want to be remembered?",
  "What makes you feel at peace?",
  "Describe a wish you thought impossible.",
  "When do you feel most creative?",
  "What are you proud of overcoming?",
  "Write about a moment of unexpected kindness.",
  "Where does your mind wander when it's quiet?",
  "What lesson keeps repeating for you?",
  "Describe a dream that feels within reach.",
  "What quality do you admire in others?",
  "How do you comfort yourself on hard days?",
  "Write about a new beginning you desire.",
  "When did you last feel deeply grateful?",
  "What habit would you like to cultivate?",
  "Describe a song that mirrors your mood.",
  "What do you need more of in your life?",
  "How do you express your authentic self?",
  "Write a letter to your future self.",
  "What belief are you questioning lately?",
  "When do you feel most connected to others?",
  "Describe a value you refuse to compromise.",
  "What memory makes you feel nostalgic?",
  "How do you nurture hope within yourself?",
  "Write about a victory, big or small.",
  "What does vulnerability mean to you?",
  "When have you felt the most courageous?",
  "Describe an act of forgiveness that changed you.",
  "What dream from childhood still lingers?",
  "How do you handle feelings of doubt?",
  "Write about something you're learning to accept.",
  "What do you want to explore more deeply?",
  "When do you feel closest to nature?",
  "Describe a kindness you want to pay forward.",
  "What would bring you more inner peace?",
  "How has a setback shaped you?",
  "Write about a time you trusted your intuition.",
  "What relationship brings you comfort?",
  "When have you felt truly content?",
  "Describe a fear you'd like to face.",
  "What message would you share with the world?",
  "How do you define success for yourself?",
  "Write about a tradition that warms your heart.",
  "What memory makes you feel brave?",
  "When do you feel most inspired?",
  "Describe a hope you cherish quietly.",
  "What habit drains your energy?",
  "How do you celebrate small victories?",
  "Write about a dream that guides you.",
  "What helps you feel grounded?",
  "When have you experienced pure joy?",
  "Describe a place you'd like to return to.",
  "What do you need to forgive yourself for?",
  "How do you show kindness to yourself?",
  "Write about a moment of unexpected beauty.",
  "What motivates you to keep going?",
  "When do you feel the most alive?",
  "Describe a meaningful conversation you had.",
  "What belief gives you strength?",
  "How do you practice mindfulness?",
  "Write about something you're curious about.",
  "What dream still feels out of reach?",
  "When did you last feel truly loved?",
  "Describe a time you felt misunderstood.",
  "What would you tell your younger self?",
  "How do you stay hopeful during challenges?",
  "Write about a change you're embracing.",
  "What piece of advice resonates with you?",
  "When have you felt proud of yourself?",
  "Describe a goal you're working toward.",
  "What does rest look like for you?",
  "How do you nourish your creativity?",
  "Write about a time you felt supported.",
  "What are you most grateful for today?",
  "When do you feel most confident?",
  "Describe a recent moment of clarity.",
  "What do you want to remember forever?",
  "How do you cultivate self-love?",
  "Write about a friendship that shaped you.",
  "What makes you feel hopeful about the future?",
  "When have you felt most at peace with yourself?",
  "Describe a place that inspires you.",
  "What do you want to let go of this week?",
  "How do you handle disappointment?",
  "Write about a goal that scares you a little.",
  "What brings you comfort on difficult days?",
  "When did you last experience wonder?",
  "Describe a moment you felt empowered.",
  "What message do you wish you could send yourself?",
  "How do you practice gratitude?",
  "Write about a dream that makes you smile.",
  "What fear no longer holds power over you?",
  "When do you feel most present?",
  "Describe a lesson you want to remember.",
  "What beauty do you see in everyday life?",
  "How do you soothe your worries?",
  "Write about a new habit you're forming.",
  "What are you most excited about right now?",
  "When have you felt true belonging?",
  "Describe a gift you can give to yourself.",
  "What memory brings you peace?",
  "How do you stay true to your values?",
  "Write about something you wish others knew about you.",
  "What dream are you nurturing quietly?",
  "When did you last feel inspired by someone?",
  "Describe a time you chose courage over comfort.",
  "What does kindness mean to you?",
  "How do you reconnect with yourself?",
  "Write about a possibility that excites you.",
  "What doubt are you ready to release?",
  "When do you feel most hopeful?",
  "Describe a memory that shaped who you are.",
  "What would you whisper to your heart today?",
  "How do you celebrate your progress?",
  "Write about a dream you've never shared.",
  "What do you cherish about your journey?",
  "When have you witnessed true compassion?",
  "Describe a goal that lights you up.",
  "What helps you feel connected to others?",
  "How do you embrace change?",
  "Write about an intention you want to set.",
  "What inspires you to be kind?",
  "When did you last surprise yourself?",
  "Describe a wish that feels daring.",
  "What role does hope play in your life?",
  "How do you release stress?",
  "Write about a dream you're manifesting.",
  "What do you need to hear right now?",
  "When have you felt deep gratitude?",
  "Describe a moment you felt powerful.",
  "What memory do you revisit often?",
  "How do you stay open to new possibilities?",
  "Write about a secret ambition.",
  "What habit brings you joy?",
  "When do you feel most generous?",
  "Describe a time you listened to your heart.",
  "What hope are you holding onto?",
  "How do you find beauty in the ordinary?",
  "Write about a way you can nurture yourself today.",
  "What dream feels closest right now?",
  "When did you last feel truly free?",
  "Describe a conversation that stayed with you.",
  "What inspires you to keep growing?",
  "How do you honor your needs?",
  "Write about a promise you made to yourself.",
  "What excites you about tomorrow?",
  "When have you felt healing begin?",
  "Describe a fear you've overcome recently.",
  "What memory brings you strength?",
  "How do you open your heart to possibility?",
  "Write about a dream that feels wild and beautiful.",
  "What makes you feel alive in this moment?",
  "When do you feel most compassionate?",
  "Describe a hope that comforts you.",
  "What inner wisdom guides you today?",
  "How do you honor your feelings?",
  "Write about something you want to learn.",
  "What dream would you pursue if money wasn't a concern?",
  "When have you felt the power of community?",
  "Describe a time you trusted the unknown.",
  "What gives you courage to be vulnerable?",
  "How do you express gratitude to others?",
  "Write about a memory that makes you laugh.",
  "What helps you feel calm?",
  "When did you last follow your intuition?",
  "Describe a goal that feels meaningful.",
  "What do you want to create in your life?",
  "How do you nourish your body and soul?",
  "Write about a dream that scares you in a good way.",
  "What connection do you cherish most?",
  "When do you feel most hopeful about the future?",
  "Describe a lesson you want to share.",
  "What intention are you carrying into today?",
  "How do you stay connected to what matters?",
  "Write about a small joy that brightened your day.",
  "What dream do you secretly believe in?",
  "When have you felt truly resilient?",
  "Describe a decision that changed your path.",
  "What inspires you to be your best self?",
  "How do you welcome new beginnings?",
  "Write about a moment you felt peaceful.",
  "What do you want to give yourself permission to do?",
  "When did you last feel awe?",
  "Describe a hope that fuels your spirit.",
  "What helps you let go of worry?",
  "How do you stay open-hearted?",
  "Write about a dream you want to nurture today.",
  "What gives you a sense of purpose?",
  "When have you felt a surge of inspiration?",
  "Describe something you're grateful to have learned.",
  "What do you hope tomorrow brings?",
  "How do you show yourself patience?",
  "Write about a memory that feels like sunshine.",
  "What dream do you want to speak into existence?",
  "When do you feel a quiet sense of joy?",
  "Describe a way you've grown this year.",
];
